--- TODO: Reconficure to use lazy loading properly: https://www.youtube.com/watch?v=idIVVAvMSbM
--- plugins need to go first
require("my.plugins")
-- require("my.toggleterm")
require("my.aerial")
require("my.autopairs")
require("my.bufferline")
require("my.colorscheme")
require("my.comment")
require("my.completions")
require("my.dap")
require("my.fidget")
require("my.gitsigns")
require("my.illuminate")
require("my.lsp")
require("my.lualine")
require("my.mappings")
require("my.misc")
require("my.options")
require("my.telescope")
require("my.todo-comments")
require("my.treesitter")
