#!/usr/bin/env bash

# https://cbrgm.net/post/2021-05-5-setup-macos/

# for this to work you must configure sudo such that
# it will be able to run the command without password
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# space config
yabai -m config --space 1                       \
    layout                       float          \
    focus_follows_mouse          off

# global config settings
yabai -m config                                 \
    mouse_follows_focus          on             \
    focus_follows_mouse          autofocus      \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               08             \
    left_padding                 08             \
    right_padding                08             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


# do not manage the following windows
yabai -m rule --add label="1Password" app="^1Password$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="BIG-IP Edge Client" app="^BIG-IP Edge Client$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Cisco AnyConnect" app="^Cisco AnyConnect Secure Mobility Client$" sticky=off manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Firmaportal" title="^Firmaportal"  manage=off
yabai -m rule --add label="Messages" app="^Messages$" title=".*" manage=off
yabai -m rule --add label="Microsoft Teams" app="^Microsoft Teams" sticky=off title!="^(Calendar)" manage=off
yabai -m rule --add label="OrbStack" app="^OrbStack$" sticky=off manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="Spotify" app="^Spotify$" sticky=off manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="YT Music" app="^YT Music$" manage=off
yabai -m rule --add label="WhatsApp" app="^WhatsApp$" sticky=off manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off

echo "yabai configuration loaded.."
